### ISSUE TITLE
[AC] [Bug/Crash] The latest version compiled incorrectly

### ISSUE THREAD

**Issue by kasting** [trickerer/Trinity-Bots#451]
The latest version compiled incorrectly
When I added MOD-ELUNA to compile, I got an error like the one below.

Severity Code Description The project file line does not display the status
Error C3668 "Eluna_PlayerScript::OnGiveXP" : Methods that contain the override speciator "override" do not override any base methods. modules D:\AZ\AzerothCore-wotlk-with-NPCBots\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp 660
Severity Code Description The project file line does not display the status
Error C4263 "void Eluna_PlayerScript::OnGiveXP(Player *,uint32 &,Unit *,uint8)" : modules D:\AZ\AzerothCore-wotlk-with-NPCBots\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp 660
Severity Code Description The project file line does not display the status
Error C4264 void PlayerScript::OnGiveXP(Player *,uint32 &,Unit *) : The virtual member function in base PlayerScript is not overwritten. Function hidden modules D:\AZ\AzerothCore-wotlk-with-NPCBots\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp 804
Severity Code Description The project file line does not display the status
Error MSB6006 link.exe exited with code 1181. worldserver	C:\Program Files\Microsoft Visual  Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	1096
Severity Code Description The project file line does not display the status
Error LNK1181 Unable to open input file ".. \.. \.. \modules\RelWithDebInfo\modules.lib”	worldserver	D:\AZbuild\050506-bot-eluna\src\server\apps\LINK	1

**Comment by trickerer** [comment]
NPCBots code doesn't affect modules.
Try to build on clean AC with Eluna. If it still fails - look for Eluna issue tracker.

**Comment by lemonmomomo** [comment]
> The latest version compiled incorrectly
> When I added MOD-ELUNA to compile, I got an error like the one below.

The latest issue with the [AC] core

Use this：
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
compile

no problem

**Comment by archer-gh** [comment]
Interestingly, I'm getting similar errors with the AutoBalance mod (mod_autobalance) on the same function, I think.  I can open another bug report on this one, but thought I'd share this snippet.

/home/azerothcore/azerothcore-npcbot/modules/mod-autobalance/src/AutoBalance.cpp:373:89: fatal error: non-virtual member function marked 'override' hides virtual member function
        void OnGiveXP(Player* player, uint32& amount, Unit* victim, uint8 /*xpSource*/) override
                                                                                        ^
/home/azerothcore/azerothcore-npcbot/src/server/game/Scripting/ScriptMgr.h:1040:18: note: hidden overloaded virtual function 'PlayerScript::OnGiveXP' declared here: different number of parameters (3 vs 4)
    virtual void OnGiveXP(Player* /*player*/, uint32& /*amount*/, Unit* /*victim*/) { }
                 ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:230: modules/CMakeFiles/modules.dir/mod-autobalance/src/AutoBalance.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1198: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by kasting** [comment]
![image](https://user-images.githubusercontent.com/83107774/236641543-73354d0b-afd7-4310-8026-e2c49c89dda5.png)
Unfortunately, errors are still reported after compiling!

**Comment by trickerer** [comment]
Caused by https://github.com/azerothcore/azerothcore-wotlk/commit/444793346de74d54a7b0b5cb9d9fc62be5772076
