### ISSUE TITLE
[AC] [Bug] [Core] Creature 31258's damage is lower than expected

### ISSUE THREAD

**Issue by SouthMemory** [trickerer/Trinity-Bots#828]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Current behaviour

within AzerothCore-wotlk-with-NPCBots, Creature 32158's attack only damage about half of expected value, 200-300, but it  should be 422 - 586(from https://db.nfuwow.com/80/?npc=31258)
I tried the original AzerothCore-wotlk, the damage is normal

### Expected behaviour

damage should be 422 - 586

### Steps to reproduce the problem

1.install AzerothCore-wotlk-with-NPCBots
2.test creature 31258's damage, it's 200-300, which is not normal

### TrinityCore or AzerothCore

AzerothCore

### Core rev. hash/commit

unknown

**Comment by Day36512** [comment]
This is an Azerothcore issue, not one directly related to Trickerer's fork at all. Suggest you put in an issue ticket on the main repo here: https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by trickerer** [comment]
No, the issue is caused by https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/a22a353.
The contradiction here is the fact that original AzerothCore factors attack power into damage the wrong way causing melee bots to do way too much damage. I just ported TC code where AP to damage calculation is the same for both players and creatures.
Didn't check TC damage for that creature but DamageModifier and classlevelstats values for unit class 1 look the same for both cores. Normally if creature deals more damage blizzlike then changing `DamageModifier` field of `creature_template` table is the way to fix it.

**Comment by SouthMemory** [comment]
You mean change the DamageModifier of creature 31258 to double its damage?
But I guess this problem influences not just 31258, but many other creatures.

**Comment by icedcolor** [comment]
@trickerer   
https://github.com/azerothcore/azerothcore-wotlk/pull/19068
This update to [AC] resulted in a compilation error.
![620](https://github.com/trickerer/Trinity-Bots/assets/19793341/05dec730-f97a-41a4-a24f-af82fd7a1c01)

**Comment by trickerer** [comment]
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/a7a60654e3cbdccac399169a36d44dbaa53873a1

**Comment by trickerer** [comment]
https://github.com/trickerer/Trinity-Bots/commit/dd5e5cf59b39d8254edbf1417a5166251eaa9547
