### ISSUE TITLE
[AC][Build]Build Error

### ISSUE THREAD

**Issue by saliven1970** [trickerer/Trinity-Bots#463]
botwanderful.h  
build on OpenEuler 22.03

In file included from /root/AzerothCore-335/src/server/game/AI/NpcBots/botwanderful.cpp:1:
/root/AzerothCore-335/src/server/game/AI/NpcBots/botwanderful.h:42:29: Error: 'recursive_mutex' Not a type name in namespace 'std'
   42 |     using mutex_type = std::recursive_mutex;
        |                             ^~~~~~~~~~~~~~~
In file included from /root/AzerothCore-335/src/server/game/AI/NpcBots/botwanderful.cpp:1:
/root/AzerothCore-335/src/server/game/AI/NpcBots/botwanderful.h:9:1: 'std::recursive_mutex'  is defined in header '\<mutex>'; did you forget to '#include \<mutex>'?
    8 | #include \<shared_mutex>
  +++ |+#include \<mutex>
    9 | #include \<unordered_map>

**Comment by trickerer** [comment]
Wow, that's rare.

Normally `<mutex>` is supposed to be included within `<shared_mutex>`. What compiler is used here?
